### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by juergengunz** [danawhite/react-native-maps-route-utils#1]
Could you please tell me how to use this?

**Comment by danawhite** [comment]
Sorry for the delayed response. This library has to be imported as a Native Module. Are you familiar with how that works?

**Comment by juergengunz** [comment]
Unfortunately I am not familiar with how that works.. could you explain? or is there any easy tutorial?

**Comment by danawhite** [comment]
@juergengunz sorry for the delayed response. The instructions in the README outline how to link the library to your React Native app. Do you have a question regarding the way to use it in your application once linked? 

Here is the official React Native documentation on how to import Native Modules into your app.

https://facebook.github.io/react-native/docs/native-modules-ios.html
